MonHan/urls.py
from django.urls import path
from . import views

app_name = 'MonHan'

urlpatterns = [
    path('', views.monster_list.as_view(), name='monster_list'),
    path('custom_list/', views.custom_list, name='custom_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
 #   path('myprofile/', include('myprofile.urls')),
 #   path('diaries/', include('diaries.urls')),
 #   path('reviews/', include('reviews.urls')),
 #   path('contact/', include('contact.urls')),
 #   path('blog/', include('blog.urls')),
    path('', include('MonHan.urls')),
]

MonHan/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

# モンスター
class Monster(models.Model):
    class Meta:
        verbose_name = "モンスター"
        verbose_name_plural = "モンスター"

    # シリーズ
    SERIES = ((1, 'IB'), (2, 'MHW'))

    # 種族名
    RACE = (
        (1, "鳥竜種"),
        (2, "牙竜種"),
        (3, "魚竜種"),
        (4, "遺存種"),
        (5, "飛竜種"),
        (6, "古龍種"),
        (7, "獣竜種")
    )

    # 選択項目
    DAISYO = ((1, "大"), (2, "小"), (3, "なし"))

    # やられ
    YARARE = ((1, '火'), (2, '水'), (3, '雷'), (4, '氷'), (5, '龍'), (6, 'なし'))

    # 状態異常
    JYOTAIIJYO = (
        (1, '毒'),
        (2, '猛毒'),
        (3, '麻痺'),
        (4, '睡眠'),
        (5, '裂傷'),
        (6, '爆破'),
        (7, '気絶'),
        (8, '防御力DOWN'),
        (9, '瘴気浸食状態'),
        (10, '泥'),
        (11, '凍結やられ'),
        (12, '火'),
        (13, 'なし')
    )

    # 基本情報
    name = models.CharField("モンスター名", max_length=200)
    series = models.IntegerField("シリーズ", choices=SERIES, null=True, blank=True)
    race = models.IntegerField("種族", choices=RACE, null=True, blank=True)
    roar = models.IntegerField("咆哮", choices=DAISYO, null=True, blank=True)
    fuatsu1 = models.IntegerField("風圧１", choices=DAISYO, null=True, blank=True)
    fuatsu2 = models.IntegerField("風圧２", choices=YARARE, null=True, blank=True)
    vibration = models.IntegerField("震動", choices=DAISYO, null=True, blank=True)
    yarare1 = models.IntegerField("やられ１", choices=YARARE, null=True, blank=True)
    yarare2 = models.IntegerField("やられ２", choices=YARARE, null=True, blank=True)
    jyotaiijyo = models.IntegerField("状態異常", choices=JYOTAIIJYO, null=True, blank=True)

    # シンボル
    SYMBOL = (
        (1, '◎'),
        (2, '〇'),
        (3, '△'),
        (4, '×'),
        (5, '？')
    )

    # 弱点属性
    jyaku_hi = models.IntegerField("弱点属性_火", choices=SYMBOL, null=True, blank=True)
    jyaku_mizu = models.IntegerField("弱点属性_水", choices=SYMBOL, null=True, blank=True)
    jyaku_kami = models.IntegerField("弱点属性_雷", choices=SYMBOL, null=True, blank=True)
    jyaku_kori = models.IntegerField("弱点属性_氷", choices=SYMBOL, null=True, blank=True)
    jyaku_ryu = models.IntegerField("弱点属性_龍", choices=SYMBOL, null=True, blank=True)

    # 状態異常耐性
    ijyo_doku = models.IntegerField("状態異常耐性_毒", choices=SYMBOL, null=True, blank=True)
    ijyo_suimin = models.IntegerField("状態異常耐性_睡眠", choices=SYMBOL, null=True, blank=True)
    ijyo_mahi = models.IntegerField("状態異常耐性_麻痺", choices=SYMBOL, null=True, blank=True)
    ijyo_kizetsu = models.IntegerField("状態異常耐性_気絶", choices=SYMBOL, null=True, blank=True)
    ijyo_meki = models.IntegerField("状態異常耐性_滅気", choices=SYMBOL, null=True, blank=True)
    ijyo_bakuha = models.IntegerField("状態異常耐性_爆破", choices=SYMBOL, null=True, blank=True)
    ijyo_nori = models.IntegerField("状態異常耐性_乗り", choices=SYMBOL, null=True, blank=True)

    # アイテム耐性
    item_senko = models.IntegerField("アイテム耐性_閃光", choices=SYMBOL, null=True, blank=True)
    item_otobaku = models.IntegerField("アイテム耐性_音爆", choices=SYMBOL, null=True, blank=True)
    item_koyashi = models.IntegerField("アイテム耐性_こやし玉", choices=SYMBOL, null=True, blank=True)
    item_shibire = models.IntegerField("アイテム耐性_シビレ罠", choices=SYMBOL, null=True, blank=True)
    item_otoshi = models.IntegerField("アイテム耐性_落し穴", choices=SYMBOL, null=True, blank=True)
    item_tsuta = models.IntegerField("アイテム耐性_ツタ", choices=SYMBOL, null=True, blank=True)
    item_wananiku = models.IntegerField("アイテム耐性_罠肉", choices=SYMBOL, null=True, blank=True)

    def __str__(self):
        return self.name

MonHan/forms.py
from django import forms
from .models import Monster
from django.db.models.fields import BLANK_CHOICE_DASH

class MonsterSearchForm(forms.Form):
    key_word = forms.CharField(
        label='モンスター名', required=False,
        widget=forms.TextInput(attrs={'class': 'input'})
    )
    race = forms.ChoiceField(
        label='', required=False,
        choices=BLANK_CHOICE_DASH + list(Monster.RACE),
    )

MonHan/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Monster
from django.views import generic
from django.db.models import Q
from .forms import MonsterSearchForm


class monster_list(generic.ListView):
    model = Monster
    ordering = 'name'

    def get_queryset(self):
        queryset = super().get_queryset()
        form = MonsterSearchForm(self.request.GET or None)
        if form.is_valid():
            # 名前で検索
            key_word = form.cleaned_data.get('key_word')
            if key_word:
                queryset = queryset.filter(Q(name__icontains=key_word))
            # 種別で検索
            race = form.cleaned_data.get('race')
            if race:
                queryset = queryset.filter(race=race)
        
        return queryset

def custom_list(request):
    return render(request, 'MonHan/custom_list.html')

MonHan/templates/MonHan/base.html
{% load monhan %}
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>モンスターリスト</title>
    <link rel="stylesheet" href="{% static 'css/MonHan.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.4/css/all.css">
    <script src="{% static 'js/common.js' %}"></script>
</head>

<body>
    <header>モンスターワールド｜アイスボーン </header>
    <main>
        <div class="links">
            <a href="{% url 'MonHan:monster_list' %}">モンスターリスト</a>
            <label>｜</label>
            <a href="{% url 'MonHan:custom_list' %}">カスタム強化リスト</a>
        </div>
        {% block content %}
        {% endblock %}
    </main>
    <div id="page_top"><a href="#"></a></div>
</body>

</html>

MonHan/templates/MonHan/custom_list.html
{% extends 'MonHan/base.html' %}

{% block content %}
<!-- カスタム強化リスト -->
<div class="customlist">
    <h1>カスタム強化リスト</h1>
    <table border="1">
        <!-- タイトル行 -->
        <tr class="list_title">
            <td>目的</td>
            <td>レア</td>
            <td>必要素材</td>
            <td>個数</td>
            <td>対象モンスター</td>
            <td>対象地帯</td>
            <td>Lv</td>
        </tr>
        <!-- ★ カスタム枠の拡張 ★ -->
        <!-- Lv1 -->
        <tr>
            <td rowspan="10">カスタム枠の拡張</td>
            <td rowspan="3">レア12 Lv1</td>
            <td>大霊脈玉</td>
            <td class="num">1</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>霊脈の古龍骨</td>
            <td class="num">3</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>生者必滅の大剛角</td>
            <td class="num">5</td>
            <td>悉くネルギガンテ</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <!-- Lv2 -->
        <tr class="colorRow">
            <td rowspan="3">レア12 Lv2</td>
            <td>大霊脈玉</td>
            <td class="num">1</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr class="colorRow">
            <td>霊脈の古龍骨</td>
            <td class="num">3</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr class="colorRow">
            <td>歴戦の煌毛</td>
            <td class="num">5</td>
            <td>歴戦ラージャ</td>
            <td>溶岩</td>
            <td class="num">7</td>
        </tr>
        <!-- Lv3 -->
        <tr>
            <td rowspan="4">レア12 Lv3</td>
            <td>大霊脈玉</td>
            <td class="num">1</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>霊脈の古龍骨</td>
            <td class="num">3</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>歴戦の殲滅角</td>
            <td class="num">5</td>
            <td>歴戦悉くネルギガンテ</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>歴戦の滅龍殻</td>
            <td class="num">5</td>
            <td>歴戦ジンオウガ亜種</td>
            <td>氷雪</td>
            <td class="num">7</td>
        </tr>
        <!-- ★ 回復能力付与 ★ -->
        <!-- Lv1 -->
        <tr class="colorRow">
            <td rowspan="9" style="background-color: #fff;">回復能力付与</td>
            <td rowspan="5">レア12 Lv1</td>
            <td>歴戦の幻惑皮</td>
            <td class="num">7</td>
            <td>歴戦ネロミェール</td>
            <td>珊瑚</td>
            <td class="num">7</td>
        </tr>
        <tr class="colorRow">
            <td rowspan="2">みなぎる雷電殻</td>
            <td rowspan="2" class="num">5</td>
            <td rowspan="2">ジンオウガ</td>
            <td>森林</td>
            <td class="num">3～5</td>
        </tr>
        <tr class="colorRow">
            <td>珊瑚</td>
            <td class="num">3～5</td>
        </tr>
        <tr class="colorRow">
            <td>霊脈の古龍骨</td>
            <td class="num">3</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr class="colorRow">
            <td>導きの龍骨【陸珊瑚】</td>
            <td class="num">1</td>
            <td>陸珊瑚地帯で稀に入手</td>
            <td>珊瑚</td>
            <td class="num"></td>
        </tr>
        <!-- Lv2 -->
        <tr>
            <td rowspan="4">レア12 Lv2</td>
            <td>歴戦の竜鱗【銀】</td>
            <td class="num">7</td>
            <td>歴戦リオレウス希少種</td>
            <td>珊瑚</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>歴戦の爆鱗</td>
            <td class="num">3</td>
            <td>歴戦紅蓮バゼル</td>
            <td>溶岩</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>霊脈の古龍骨</td>
            <td class="num">3</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>導きの龍骨【溶岩】</td>
            <td class="num">1</td>
            <td>溶岩地帯で稀に入手</td>
            <td>溶岩</td>
            <td class="num"></td>
        </tr>
        <!-- ★ 会心率強化 ★ -->
        <!-- Lv1 -->
        <tr class="colorRow">
            <td rowspan="12" style="background-color: #fff;">会心率強化</td>
            <td rowspan="3">レア12 Lv1</td>
            <td>灼熱の断剣尾</td>
            <td class="num">9</td>
            <td>ディノバルド</td>
            <td>荒地</td>
            <td class="num">3～5</td>
        </tr>
        <tr class="colorRow">
            <td>龍脈の重竜骨</td>
            <td class="num">3</td>
            <td>何でも？</td>
            <td>導き</td>
            <td class="num">2～3</td>
        </tr>
        <tr class="colorRow">
            <td>泰然たる結晶</td>
            <td class="num">3</td>
            <td>荒地地帯で入手</td>
            <td>荒地</td>
            <td class="num"></td>
        </tr>
        <!-- Lv2 -->
        <tr>
            <td rowspan="5">レア12 Lv2</td>
            <td>歴戦の紅きたてがみ</td>
            <td class="num">7</td>
            <td>歴戦テオテスカトル</td>
            <td>溶岩</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td rowspan="2">蒼炎のたてがみ</td>
            <td rowspan="2" class="num">5</td>
            <td rowspan="2">ナナテスカトリ</td>
            <td>溶岩</td>
            <td class="num">5～6</td>
        </tr>
        <tr>
            <td>荒地</td>
            <td class="num">5～6</td>
        </tr>
        <tr>
            <td>霊脈の古龍骨</td>
            <td class="num">3</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>導きの結晶【荒地】</td>
            <td class="num">1</td>
            <td>荒地地帯で稀に入手</td>
            <td>荒地</td>
            <td class="num"></td>
        </tr>
        <!-- Lv3 -->
        <tr class="colorRow">
            <td rowspan="4">レア12 Lv3</td>
            <td>歴戦の殲滅角</td>
            <td class="num">7</td>
            <td>歴戦ネルギガンテ</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr class="colorRow">
            <td>歴戦の氷牙</td>
            <td class="num">5</td>
            <td>歴戦ベリオロス</td>
            <td>氷雪</td>
            <td class="num">6～7</td>
        </tr>
        <tr class="colorRow">
            <td>霊脈の古龍骨</td>
            <td class="num">3</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr class="colorRow">
            <td>導きの結晶【氷雪】</td>
            <td class="num">1</td>
            <td>氷雪地帯で稀に入手</td>
            <td>氷雪</td>
            <td class="num"></td>
        </tr>
        <!-- ★ 攻撃力強化 ★ -->
        <!-- Lv1 -->
        <tr>
            <td rowspan="10">攻撃力強化</td>
            <td rowspan="5">レア12 Lv1</td>
            <td rowspan="2">歴戦の鋼翼</td>
            <td rowspan="2" class="num">7</td>
            <td rowspan="2">歴戦クシャルダオラ</td>
            <td>溶岩</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>森林</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>血に染まる漆黒皮</td>
            <td class="num">5</td>
            <td>怒り喰らうイビルジョー</td>
            <td>氷雪</td>
            <td class="num">5～6</td>
        </tr>
        <tr>
            <td>霊脈の古龍骨</td>
            <td class="num">3</td>
            <td>歴戦古龍</td>
            <td>導き</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>龍脈に眠る大骨</td>
            <td class="num">5</td>
            <td>森林地帯で入手</td>
            <td>森林</td>
            <td class="num"></td>
        </tr>
        <!-- Lv2 -->
        <tr class="colorRow">
            <td rowspan="5">レア12 Lv2</td>
            <td>歴戦の竜鱗【銀】</td>
            <td class="num">7</td>
            <td>歴戦リオレウス希少種</td>
            <td>珊瑚</td>
            <td class="num">7</td>
        </tr>
        <tr class="colorRow">
            <td rowspan="2">闘気あふれる煌毛</td>
            <td rowspan="2" class="num">5</td>
            <td rowspan="2">ラージャン</td>
            <td>導き</td>
            <td class="num">5～7</td>
        </tr>
        <tr class="colorRow">
            <td>溶岩</td>
            <td class="num">4～6</td>
        </tr>
        <tr class="colorRow">
            <td>霊脈の剛竜骨</td>
            <td class="num">3</td>
            <td>歴戦</td>
            <td>導き</td>
            <td class="num">5～6</td>
        </tr>
        <tr class="colorRow">
            <td>龍脈に焦がされし蛮骨</td>
            <td class="num">3</td>
            <td>溶岩地帯で入手</td>
            <td>溶岩</td>
            <td class="num"></td>
        </tr>
        <!-- ★ 属性強化 ★ -->
        <!-- Lv1 -->
        <tr>
            <td rowspan="13">属性・状態異常強化</td>
            <td rowspan="5">レア12 Lv1</td>
            <td>歴戦の重油殻</td>
            <td class="num">7</td>
            <td>歴戦ラドバルキン</td>
            <td>瘴気</td>
            <td class="num">4～7</td>
        </tr>
        <tr>
            <td rowspan="2">命断ち切る惨爪</td>
            <td rowspan="2" class="num">5</td>
            <td rowspan="2">オドガロン</td>
            <td>珊瑚</td>
            <td class="num">3～4</td>
        </tr>
        <tr>
            <td>瘴気</td>
            <td class="num">2～4</td>
        </tr>
        <tr>
            <td>霊脈の重竜骨</td>
            <td class="num">3</td>
            <td>歴戦</td>
            <td>導き</td>
            <td class="num">3</td>
        </tr>
        <tr>
            <td>黄昏の結晶</td>
            <td class="num">3</td>
            <td>瘴気地帯で入手</td>
            <td>瘴気</td>
            <td class="num"></td>
        </tr>
        <!-- Lv2 -->
        <tr class="colorRow">
            <td rowspan="4">レア12 Lv2</td>
            <td>戦慄の黒アギト</td>
            <td class="num">9</td>
            <td>ティガレックス亜種</td>
            <td>瘴気</td>
            <td class="num">6</td>
        </tr>
        <tr class="colorRow">
            <td>宵闇より昏き牙</td>
            <td class="num">5</td>
            <td>死を纏うヴァルハザク</td>
            <td>瘴気</td>
            <td class="num">5～6</td>
        </tr>
        <tr class="colorRow">
            <td>龍脈の古龍骨</td>
            <td class="num">3</td>
            <td>古龍</td>
            <td>導き</td>
            <td class="num">5</td>
        </tr>
        <tr class="colorRow">
            <td>導きの結晶【瘴気】</td>
            <td class="num">1</td>
            <td>瘴気地帯で稀に入手</td>
            <td>瘴気</td>
            <td class="num"></td>
        </tr>
        <!-- Lv3 -->
        <tr>
            <td rowspan="4">レア12 Lv3</td>
            <td>歴戦の竜鱗【金】</td>
            <td class="num">7</td>
            <td>歴戦リオレイア希少種</td>
            <td>荒地</td>
            <td class="num">7</td>
        </tr>
        <tr>
            <td>つややかな黒曜甲</td>
            <td class="num">5</td>
            <td>ブラキディオス</td>
            <td>溶岩</td>
            <td class="num">2～5</td>
        </tr>
        <tr>
            <td>霊脈の剛竜骨</td>
            <td class="num">3</td>
            <td>歴戦</td>
            <td>導き</td>
            <td class="num">5～6</td>
        </tr>
        <tr>
            <td>導きの結晶【溶岩】</td>
            <td class="num">1</td>
            <td>溶岩地帯で稀に入手</td>
            <td>溶岩</td>
            <td class="num"></td>
        </tr>
    </table>
</div>
{% endblock %}

MonHan/templates/MonHan/monster_list.html
{% extends 'MonHan/base.html' %}
{% load monhan %}

{% block content %}
<!-- ページタイトル -->
<div class="page_title">
    <h1>モンスターリスト</h1>
</div>

<!-- 絞り込み条件 -->
<div class="filter">
    {% create_search_form request %}
</div>

<!-- モンスターリスト -->
<div class="list">
    <!-- 一覧タイトル -->
    <div class="list_header list_title">
        <div class="name">
            モンスター名
        </div>
        <div class="race">
            種族
        </div>
        <div class="series">
            シリーズ
        </div>
    </div>

    {% for mons in monster_list %}
    <!-- モンスター名を表示する行 -->
    <input id="acd-check{{ forloop.counter }}" class="acd-checkbox" type="checkbox">
    <label class="acd-label list_header" for="acd-check{{ forloop.counter }}">
        <div class="name">
            {{ mons.name }}
        </div>
        <div class="race">
            {{ mons.get_race_display }}
        </div>
        <div class="series">
            {{ mons.get_series_display}}
        </div>
    </label>

    <!-- アコーディオンで非表示にする範囲 -->
    <div class="acd-content">
        <!-- 咆哮とか -->
        <div class="details_title">
            <span>咆哮</span>
            <span>風圧</span>
            <span>震動</span>
            <span>やられ</span>
            <span>状態異常</span>
        </div>
        <div class="details_item">
            <span>{{ mons.get_roar_display }}</span>
            <span>{{ mons.get_fuatsu1_display }}</span>
            <span>{{ mons.get_vibration_display }}</span>
            <span>{{ mons.get_yarare1_display }}</span>
            <span>{{ mons.get_jyotaiijyo_display }}</span>
        </div>
        <!-- 弱点属性を表示する行 -->
        <div id="jyaku">
            <div class="details_header">
                <label>弱点属性</label>
            </div>
            <div class="details_title">
                <span>火</span>
                <span>水</span>
                <span>雷</span>
                <span>氷</span>
                <span>龍</span>
            </div>
            <div class="details_item">
                <span>{{ mons.get_jyaku_hi_display}}</span>
                <span>{{ mons.get_jyaku_mizu_display}}</span>
                <span>{{ mons.get_jyaku_kami_display}}</span>
                <span>{{ mons.get_jyaku_kori_display}}</span>
                <span>{{ mons.get_jyaku_ryu_display}}</span>
            </div>
        </div>
        <!-- 状態異常耐性を表示する行 -->
        <div id="ijyo">
            <div class="details_header">
                <label>状態異常耐性</label>
            </div>
            <div class="details_title">
                <span>毒</span>
                <span>睡眠</span>
                <span>麻痺</span>
                <span>気絶</span>
                <span>滅気</span>
                <span>爆破</span>
                <span>乗り</span>
            </div>
            <div class="details_item">
                <span>{{ mons.get_ijyo_doku_display}}</span>
                <span>{{ mons.get_ijyo_suimin_display}}</span>
                <span>{{ mons.get_ijyo_mahi_display}}</span>
                <span>{{ mons.get_ijyo_kizetsu_display}}</span>
                <span>{{ mons.get_ijyo_meki_display}}</span>
                <span>{{ mons.get_ijyo_bakuha_display}}</span>
                <span>{{ mons.get_ijyo_nori_display}}</span>
            </div>
        </div>
        <!-- アイテム耐性を表示する行 -->
        <div id="item">
            <div class="details_header">
                <label>アイテム耐性</label>
            </div>
            <div class="details_title">
                <span>閃光</span>
                <span>音爆</span>
                <span>こやし玉</span>
                <span>シビレ罠</span>
                <span>落し穴</span>
                <span>ツタ</span>
                <span>罠肉</span>
            </div>
            <div class="details_item">
                <span>{{ mons.get_item_senko_display}}</span>
                <span>{{ mons.get_item_otobaku_display}}</span>
                <span>{{ mons.get_item_koyashi_display}}</span>
                <span>{{ mons.get_item_shibire_display}}</span>
                <span>{{ mons.get_item_otoshi_display}}</span>
                <span>{{ mons.get_item_tsuta_display}}</span>
                <span>{{ mons.get_item_wananiku_display}}</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

MonHan/templates/MonHan/search_form.html
<p class="menu-label">検索フォーム</p>
<form action="{% url 'MonHan:monster_list' %}" method="GET">
    <div class="field">
        <div class="control">
            {{ form.key_word }}
        </div>
    </div>
    <div class="field">
        <div class="control">
            {{ form.race }}
        </div>
    </div>

    <button class="button is-primaty" type="submit">検索</button>
</form>