MonHan/urls.py
from django.urls import path
from . import views

app_name = 'MonHan'

urlpatterns = [
    path('', views.monster_list.as_view(), name='monster_list'),
    path('custom_list/', views.custom_list, name='custom_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
 #   path('myprofile/', include('myprofile.urls')),
 #   path('diaries/', include('diaries.urls')),
 #   path('reviews/', include('reviews.urls')),
 #   path('contact/', include('contact.urls')),
 #   path('blog/', include('blog.urls')),
    path('', include('MonHan.urls')),
]

sample/myprofile/urls.py
from django.urls import path
from . import views

app_name = 'myprofile'

urlpatterns = [
    path('', views.top, name='top'),
    path('resume/', views.resume, name='resume'),
]

sample/myprofile/models.py
from django.db import models

# Create your models here.

sample/myprofile/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render

# Create your views here.
def top(request):
    context = {
        'name': 'たろう',
    }
    return render(request, 'myprofile/top.html', context)
    #html = loader.render_to_string('myprofile/top.html', context=context, request=request)
    #return HttpResponse(html)

def resume(request):
    return render(request, 'myprofile/resume.html')

sample/myprofile/templates/myprofile/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <header>Taro's Profile</header>

        <nav>
            <a href="{% url 'myprofile:top' %}">TOP</a>
            <a href="{% url 'myprofile:resume' %}">Resume</a>
        </nav>

        {% block content %}{% endblock %}
    </body>
</html>

sample/myprofile/templates/myprofile/resume.html
{% extends 'myprofile/base.html' %}

{% block title %}Taro's Profile - 職務経歴{% endblock %}

{% block content %}
    <h1>履歴・職務経歴</h1>

    <h2>職歴</h2>
    <table>
        <tr>
            <th>2015</th>
            <td>〇〇株式会社にて、CTOとして活躍</td>
        </tr>
    </table>

    <h2>学歴</h2>
    
{% endblock %}

sample/myprofile/templates/myprofile/top.html
{% extends 'myprofile/base.html' %}

{% block title %}Taro's Profile{% endblock %}

{% block content %}
    <h1>{{ name }}についての概要</h1>
    <p>東京にすんでいる、40歳になったエンジニアです。</p>

    <h2>趣味</h2>
    <ul>
        <li>映画</li>
    </ul>
    他のコンテンツ...
{% endblock %}