MonHan/urls.py
from django.urls import path
from . import views

app_name = 'MonHan'

urlpatterns = [
    path('', views.monster_list.as_view(), name='monster_list'),
    path('custom_list/', views.custom_list, name='custom_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
 #   path('myprofile/', include('myprofile.urls')),
 #   path('diaries/', include('diaries.urls')),
 #   path('reviews/', include('reviews.urls')),
 #   path('contact/', include('contact.urls')),
 #   path('blog/', include('blog.urls')),
    path('', include('MonHan.urls')),
]

sample/reviews/urls.py
from django.urls import path
from . import views

app_name= 'reviews'

urlpatterns = [
    path('', views.ReviewList.as_view(), name='review_list'),
    path('detail/<int:pk>/', views.ReviewDetail.as_view(), name='review_detail'),
    path('create/', views.ReviewCreate.as_view(), name='review_create'),
    path('update/<int:pk>/', views.ReviewUpdate.as_view(), name='review_update'),
    path('delete/<int:pk>/', views.ReviewDelete.as_view(), name='review_delete'),
]

sample/reviews/models.py
from django.db import models
from django.utils import timezone

class Review(models.Model):
    STARS = (
        (1, '☆'),
        (2, '☆☆'),
        (3, '☆☆☆'),
        (4, '☆☆☆☆'),
        (5, '☆☆☆☆☆')
    )

    store_name = models.CharField('店名', max_length=255)
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('口コミテキスト', blank=True)
    stars = models.IntegerField('星の数', choices=STARS)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.title

sample/reviews/forms.py
from django import forms
from .models import Review

class ReviewCreateForm(forms.ModelForm):
    class Meta:
        model = Review
        #fields = '__all__'
        exclude = ('created_at',)

sample/reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Review
from .forms import ReviewCreateForm
from django.views import generic
from django.urls import reverse_lazy

class ReviewList(generic.ListView):
    model = Review

class ReviewDetail(generic.DetailView):
    model = Review

class ReviewCreate(generic.CreateView):
    model = Review
    form_class = ReviewCreateForm
    success_url = reverse_lazy('reviews:review_list')

class ReviewUpdate(generic.UpdateView):
    model = Review
    form_class = ReviewCreateForm
    success_url = reverse_lazy('reviews:review_list')

class ReviewDelete(generic.DeleteView):
    model = Review
    success_url = reverse_lazy('reviews:review_list')

# get_object_or_404 を使用しない場合の書き方
""" 
def review_detail(request, pk):
    
    try:
        review = Review.objects.get(pk=pk)
    except Review.DoesNotExist:
        raise Http404
    
    context = {
        'review': review,
    }
    return render(request, 'reviews/review_detail.html', context)
 """

sample/reviews/templates/reviews/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device_width, initial-scale=1">
        <title>色んなお店の口コミサイト</title>
        <style>
            * {
                margin: 0;
            }
            body {
                color: #333;
            }
            body > header {
                font-size: 40px;
                background-color: #000;
                color: #fff;
                padding: 10px 30px;
            }
            main {
                margin-top: 20px;
                padding: 0 30px;
            }
            main > h1 {
                margin-bottom: 20px;
            }
            main> article {
                padding: 0 30px;
                margin-bottom: 20px;
            }
            .errorlist {
                margin: 0;
                padding: 0;
                list-style-type: none;
                color: red;
            }
            form > p {
                margin-bottom: 20px;
            }
            p > span.helptext {
                font-size: 14px;
                color: #999;
            }
            p > label {
                display: block;
            }
            p > input, p > textarea, p > select {
                width: 400px;
                padding: 6px 12px;
                box-sizing: border-box;
                border-radius: 4px;
                border: solid 1px #999;
            }
        </style>
    </head>
    <body>
        <header>色んなお店の口コミサイト</header>
        <main>
            {% block content %}{% endblock %}
        </main>
    </body>
</html>

sample/reviews/templates/reviews/review_confirm_delete.html
{% extends 'reviews/base.html' %}

{% block content %}
    <p>{{ review.store_name }}のレビューを削除します。よろしいですか。</p>
    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
{% endblock %}

sample/reviews/templates/reviews/review_detail.html
{% extends 'reviews/base.html' %}

{% block content %}
    <article>
        <h1>{{ review.store_name }}</h1>
        <p>{{ review.get_stars_display }} - {{ review.title }}</p>
        {{ review.text | linebreaks }}
    </article>
    <a href="{% url 'reviews:review_update' review.pk %}">更新</a>
    <a href="{% url 'reviews:review_delete' review.pk %}">削除</a>
{% endblock %}

sample/reviews/templates/reviews/review_form.html
{% extends 'reviews/base.html' %}
{% block content %}
    <form action="" method="POST">
        {{ form.as_p }}
        <!--作成ページに作成日を表示しないための条件文-->
        {% if form.instance.pk %}
            <p>{{ form.instance.created_at }}</p>
        {% endif %}
        <!--CSRFという攻撃を防ぐための記述 POSTには必須-->
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

sample/reviews/templates/reviews/review_list.html
{% extends 'reviews/base.html' %}

{% block content %}
    <h1>口コミ一覧</h1>
    {% for review in review_list %}
        <article>
            <h2><a href="{% url 'reviews:review_detail' review.pk %}">{{ review.store_name }}</a></h2>
            <p>{{ review.get_stars_display }} - {{ review.title }}</p>
        </article>
    {% endfor %}
    <a href="{% url 'reviews:review_create' %}">口コミ作成ページへ</a>
{% endblock %}